/**
 * Force the webpack bundler for `theia build`.
 *
 * Recent @theia/cli defaults to the esbuild pipeline when no bundler config is
 * present, but esbuild does not understand the webpack-style `~` tilde prefix
 * that Theia's own CSS uses (e.g. @theia/git's `~octicons/build/svg/*.svg`), so
 * the build fails with: Could not resolve "~octicons/build/svg/git-commit.svg".
 * The webpack css-loader resolves `~` to node_modules, so we pin webpack here.
 *
 * `gen-webpack.config.js` / `gen-webpack.node.config.js` are regenerated by the
 * generate step that runs at the start of every `theia build`; do not edit them.
 */
// @ts-check
const configs = require('./gen-webpack.config.js');
const nodeConfig = require('./gen-webpack.node.config.js');

module.exports = [
    ...configs,
    nodeConfig.config
];
